---

# For use with pre-commit.
# See usage instructions at https://pre-commit.com

- id: ansible-review
  name: Ansible-review
  description: This hook runs ansible-review.
  entry: ansible-review
  language: python
  files: \.(yaml|yml)$
